# Generated by Django 3.2.4 on 2021-06-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('excellence_rating', models.IntegerField()),
                ('rate_week_regular', models.FloatField()),
                ('rate_week_loyalty', models.FloatField()),
                ('rate_weekend_regular', models.FloatField()),
                ('rate_weekend_loyalty', models.FloatField()),
            ],
        ),
    ]
